#!/bin/bash

PL_QUESTION_PATH=/Users/christinayang/Documents/GitHub/OPB/pl-opb-ind100/questions/FM
WRITE_PATH=/Users/christinayang/Documents/GitHub/OPB/instructor_stats_bank/source/unsorted

array[0]="sophivar"
array[1]="alebuiles"
array[2]="IRIDIXVdt"
array[3]="SamuelStreet"
array[4]="camirr"

size=${#array[@]}
index=$(($RANDOM % $size))
REVIEWER=${array[$index]}
echo "REVIEWER: $REVIEWER"

DIR=w-ready
for FILE in $DIR/*/*.md;
do
    echo $FILE
    cd /Users/christinayang/Documents/GitHub/OPB/instructor_stats_bank
    echo "HII"
    echo $FILE
    git reset --hard origin/main
    echo $FILE
    out="$(basename $FILE .md)"
    BRANCH_NAME="auto_$(basename $FILE .md)"
    INFO_PATH=/Users/christinayang/Documents/GitHub/OPB/opb-utils/info/$out
    ASSIGN=$(cat $INFO_PATH/assign.txt)
    ISSUE_NUMBER=$(cat $INFO_PATH/issue_number.txt)
    echo $ASSIGN
    echo $ISSUE_NUMBER
    echo $BRANCH_NAME
    git checkout -B $BRANCH_NAME
    cp -R /Users/christinayang/Documents/GitHub/OPB/opb-utils/$DIR/$out $WRITE_PATH
    echo "ADDING $WRITE_PATH/$out"
    ls
    git add $WRITE_PATH/$out
    git commit -m "Autogenerated template"
    git push --force-with-lease -u origin $BRANCH_NAME
    echo "PUSHED $FILE SUCCESSFULLY"
    gh pr reopen $BRANCH_NAME
    gh pr edit $BRANCH_NAME --add-label "check_syntax" --add-reviewer $REVIEWER
    gh pr ready $BRANCH_NAME
    sleep 2
done
